name: Frontend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npx vite build

      - name: Build Docker image
        run: docker build -t kaiburr-frontend:latest .

      - name: Test Docker container
        run: docker run -d -p 3000:80 kaiburr-frontend:latest

